title:              Quantum Musings
email:              reach2sayan@gmail.com
description:        My personal blog where I write about Materials Science and Machine Learning
author:             Sayan Samanta
baseurl:            "/quantum_musings"
url:                "https://reach2sayan.github.io"

# Social Profiles
twitter_username:   reach2sayan
github_username:    reach2sayan
facebook_username:  justAnotherSaiyan
linkedin_username:  sayan-samanta-90592a23
instagram_username: flying_saiyan

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
highlighter: 	    rouge
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sayan Samanta"
resume_title:                   "PhD Candidate — Brown University | School of Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "reach2sayan@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 (401) 699-1340"
resume_contact_address:         "11 Alumni Avenue, Apt. 23, Providence, RI - 02906"

resume_header_contact_info:     "11 Alumni Avenue, RI - 02906 • (401) 699-1340 • reach2sayan@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>My research interest lies in applying Data Science and Machine Learning techniques to the field of Ab-Initio Computational Materials Science. Currently in my 4th year of PhD program also pursuing a Doctoral Certification in Data Science.
<br><br>
<b>Tools:</b> TensorFlow, PyTorch, VASP, ATAT, Python, C++</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_projects:        true
resume_section_experience:      true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
#Fresume_section_interests:       true
resume_section_publications:    true
resume_section_confandshops:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      false

# Design settings
resume_theme:                   default
